---
name: Lint and Check Breaking Changes

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Buf Init
        uses: bufbuild/buf-setup-action@v1.45.0
        with:
          version: latest
      - name: Buf Lint
        run: |
          buf lint
...
